name = "GlacioTeaching"
uuid = "d4a64349-7d63-4304-bc85-347e5f0acb8c"
authors = ["Mauro Werder <mauro3@runbox.com> and contributors"]
version = "0.1.0"

[deps]
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
Literate = "2"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
